# Generated by Django 5.1.4 on 2025-01-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0004_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoryy',
        ),
    ]
