# Generated by Django 5.1.4 on 2025-01-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0005_rename_category_post_categoryy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryy',
            new_name='category',
        ),
    ]
